# 端口
server:
  port: 8000
#apollo
apollo:
  bootstrap:
    enabled:  true
    eagerLoad:
      enable: false # 是否开启 Apollo 支持日志级别的加载时机。默认为 false
    namespaces: application,sentinel-rule
# 应用名称
spring:
  application:
    name: gateway-master
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 8081

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: false #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，# 这个router将以服务名开头的请求路径转发到对应的服务
#          lower-case-service-id: true #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了,比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上
#      routes:
#      - id: zyd_route11
#        uri: lb://gateway-service
#        order: -1
#        predicates:
#        - Path=/routezyd/zyd
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

#黑名单
black:
  enable: false
  black-list: lx,zyd

ribbon-config-demo.ribbon.listOfServers=localhost:8081,localhost:8083


logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug